platform :ios, '11.0'

target 'UXSDKBetaSampleApp' do
  use_frameworks!
  pod 'DJI-SDK-iOS', '~> 4.13'
  pod 'DJIWidget', '~> 1.6.3'
  pod 'DJI-UXSDK-iOS-Beta', '~> 0.3'
  pod 'DJIFlySafeDatabaseResource', '~> 01.00.01.17'
  pod 'iOS-Color-Picker'
end