
platform :ios, '11.0'

target 'UXSDKBetaSampleApp' do
  use_frameworks!

  pod 'iOS-Color-Picker'
  pod 'DJI-UXSDK-iOS-Beta', '0.4.1'

end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |configuration|
      target.build_settings(configuration.name)['ARCHS'] = '$(ARCHS_STANDARD)'
    end
  end
end