source 'ssh://git@us003.fly-access.com:7999/msdk/ios-internal-cocoapods-specs.git'
source 'https://github.com/CocoaPods/Specs.git'


platform :ios, '11.0'

target 'UXSDKBetaSample' do
  use_frameworks!
  pod 'DJI-SDK-iOS', '~> 4.12'
  pod 'DJIWidget', '~> 1.6.2'
  pod 'DJI-UXSDK-iOS-Beta', '~> 0.2'
  pod 'iOS-Color-Picker'
end
